"""
Report generation service – Markdown and PDF.
"""
from __future__ import annotations

import logging
import os
from datetime import datetime
from typing import Dict, Any

from config import settings

logger = logging.getLogger(__name__)


def generate_markdown_report(analysis_id: str, repo_name: str, results: Dict[str, Any]) -> str:
    """Generate a Markdown report from analysis results. Returns file path."""
    md = _build_markdown(repo_name, results)
    path = os.path.join(settings.REPORTS_DIR, f"{analysis_id}_report.md")
    os.makedirs(settings.REPORTS_DIR, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(md)
    logger.info("Markdown report saved: %s", path)
    return path


def _build_markdown(repo_name: str, results: Dict) -> str:
    now = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
    sections = [f"# RepoMind AI Report – {repo_name}\n\n_Generated: {now}_\n\n---\n"]

    # Repository scan
    if repo := results.get("repository"):
        sections.append(f"## 📁 Repository Overview\n\n{repo.get('summary', '')}\n\n")
        sections.append(f"- **Primary Language**: {repo.get('primary_language', 'N/A')}\n")
        sections.append(f"- **Frameworks**: {', '.join(repo.get('frameworks', []))}\n")
        sections.append(f"- **Total Files**: {repo.get('total_files', 0)}\n")
        sections.append(f"- **Total Lines**: {repo.get('total_lines', 0)}\n\n")

    # Architecture
    if arch := results.get("architecture"):
        sections.append(f"## 🏛️ Architecture\n\n{arch.get('overview', '')}\n\n")
        for sec in arch.get("sections", [])[:3]:
            sections.append(f"### {sec['title']}\n\n{sec['description']}\n\n")

    # Code Review
    if rev := results.get("review"):
        sections.append(f"## 🔍 Code Review\n\n{rev.get('summary', '')}\n\n")
        sections.append(f"| Severity | Count |\n|---|---|\n")
        sections.append(f"| 🔴 Critical | {rev.get('critical_count', 0)} |\n")
        sections.append(f"| 🟠 High | {rev.get('high_count', 0)} |\n")
        sections.append(f"| 🟡 Medium | {rev.get('medium_count', 0)} |\n")
        sections.append(f"| 🟢 Low | {rev.get('low_count', 0)} |\n\n")
        for issue in rev.get("issues", [])[:5]:
            sections.append(f"**{issue['severity'].upper()} – {issue['title']}**\n\n")
            sections.append(f"{issue['description']}\n\n_Suggestion: {issue['suggestion']}_\n\n")

    # Security
    if sec_data := results.get("security"):
        sections.append(f"## 🛡️ Security\n\n{sec_data.get('summary', '')}\n\n")
        for vuln in sec_data.get("vulnerabilities", [])[:5]:
            sections.append(f"**{vuln['severity'].upper()} – {vuln['title']}**\n\n")
            sections.append(f"{vuln['description']}\n\n_Recommendation: {vuln['recommendation']}_\n\n")

    # Performance
    if perf := results.get("performance"):
        sections.append(f"## ⚡ Performance\n\n{perf.get('summary', '')}\n\n")
        for finding in perf.get("findings", [])[:4]:
            sections.append(f"**[{finding['impact'].upper()}] {finding['title']}**\n\n")
            sections.append(f"{finding['description']}\n\n_Suggestion: {finding['suggestion']}_\n\n")

    # Scoring
    if score := results.get("scoring"):
        sections.append(f"## 📈 Project Scores\n\n")
        sections.append(f"| Category | Score |\n|---|---|\n")
        for cat in ["architecture", "security", "performance", "documentation", "maintainability"]:
            d = score.get(cat, {})
            sections.append(f"| {cat.title()} | {d.get('score', 'N/A')}/10 |\n")
        sections.append(f"\n**Overall Score: {score.get('overall', 'N/A')}/10 – Grade: {score.get('grade', 'N/A')}**\n\n")

    sections.append("\n---\n_Report generated by RepoMind AI_\n")
    return "".join(sections)


def generate_pdf_report(analysis_id: str, repo_name: str, results: Dict[str, Any]) -> str:
    """Generate a PDF report. Returns file path."""
    path = os.path.join(settings.REPORTS_DIR, f"{analysis_id}_report.pdf")
    os.makedirs(settings.REPORTS_DIR, exist_ok=True)
    try:
        from reportlab.lib.pagesizes import letter  # type: ignore
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer  # type: ignore
        from reportlab.lib.styles import getSampleStyleSheet  # type: ignore

        doc = SimpleDocTemplate(path, pagesize=letter)
        styles = getSampleStyleSheet()
        story = []

        story.append(Paragraph(f"RepoMind AI Report – {repo_name}", styles["Title"]))
        story.append(Spacer(1, 12))

        if score := results.get("scoring"):
            story.append(Paragraph("Project Scores", styles["Heading1"]))
            for cat in ["architecture", "security", "performance", "documentation", "maintainability"]:
                d = score.get(cat, {})
                story.append(Paragraph(f"{cat.title()}: {d.get('score', 'N/A')}/10", styles["Normal"]))
            story.append(Paragraph(f"Overall: {score.get('overall', 'N/A')}/10", styles["Heading2"]))
            story.append(Spacer(1, 12))

        if rev := results.get("review"):
            story.append(Paragraph("Code Review Summary", styles["Heading1"]))
            story.append(Paragraph(rev.get("summary", ""), styles["Normal"]))

        doc.build(story)
        logger.info("PDF report saved: %s", path)
    except ImportError:
        logger.warning("reportlab not installed – falling back to text PDF")
        with open(path.replace(".pdf", ".txt"), "w") as f:
            f.write(_build_markdown(repo_name, results))
        return path.replace(".pdf", ".txt")

    return path
